---
title: "Untitled"
format: html
editor: visual
---

# Aviv

## Recalculate using only trans-QTLs

Kirk: "Many/Most QTLs do not harbor ILC-expressed genes". Is this statement out of all QTLs or out of transQTLs (trans eQTLs + program QTLs + proportion QTLs)? 48% is quoted in the Results which is just under half, but it was unclear if it's out of all QTLs or out of trans. Because cis eQTLs are moot (by definition for those there is a proximal ILC gene) I'd rather have the % out of trans QTLs, but was not sure if it's 48% ("many") or more ("most"). Please state % here in the doc in terms of % out of trans QTLs

Response: in qtl-counts.R filess

## Threshold used for topics

Kirk: Topics (ii). What threshold was used to consider a gene a member of a topic (program)? Missing from the Methods. Please write here and I will incorporate.

    Response: 
      - thresholed by LDA probabilities
      
    

## Chromosome 2 Loci

"QTL mapping identified 41 cytokine QTLs (Figure 4E and S4C, STAR Methods), including two strong loci in chromosome 2 \[AR1\] \[AR2\] associated with multiple cytokine QTLs: the HoxD cluster and a locus harboring Sec23b, a gene critical for cytokine secretion from T cells73." Are these two loci on Chr2 the same as the trans loci in Figure 1E (also in chromosome 2)?. Please answer here.

   - answered previsouly in an email to Miao on 11/23/2023 at 9:28p


# Mioa

Could you check the expression of these eGenes in these figures? I do not have the data.

In all the following figures, for the LOD scores for an expression (eQTL) trait, please list also the cell type in which it is being associated (ie gene name + ILC type; if all of them then “all”):

Figures 1F, 7A, 7E
SFigures S4F, S6B (currently S6D); S6F (currently S6H)

This is the last one thing before we are good to go!


```{r}

```

